// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsOn(eventName: string, callback: (...data: any) => void): () => void;

export function EventsOff(eventName: string, ...additionalEventNames: string[]): void;

export function EventsOnce(eventName: string, callback: (...data: any) => void): void;

export function EventsOnMultiple(eventName: string, callback: (...data: any) => void, maxCallbacks: number): () => void;

export function EventsEmit(eventName: string, ...data: any): void;