// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventsOn(eventName, callback) {
  return window.runtime.EventsOn(eventName, callback);
}

export function EventsOff(eventName, ...additionalEventNames) {
  return window.runtime.EventsOff(eventName, ...additionalEventNames);
}

export function EventsOnce(eventName, callback) {
  return window.runtime.EventsOnce(eventName, callback);
}

export function EventsOnMultiple(eventName, callback, maxCallbacks) {
  return window.runtime.EventsOnMultiple(eventName, callback, maxCallbacks);
}

export function EventsEmit(eventName, ...data) {
  return window.runtime.EventsEmit(eventName, ...data);
}

export function WindowReload() {
  return window.runtime.WindowReload();
}

export function WindowReloadApp() {
  return window.runtime.WindowReloadApp();
}

export function WindowSetAlwaysOnTop(b) {
  return window.runtime.WindowSetAlwaysOnTop(b);
}

export function WindowSetSystemDefaultTheme() {
  return window.runtime.WindowSetSystemDefaultTheme();
}

export function WindowSetLightTheme() {
  return window.runtime.WindowSetLightTheme();
}

export function WindowSetDarkTheme() {
  return window.runtime.WindowSetDarkTheme();
}

export function WindowCenter() {
  return window.runtime.WindowCenter();
}

export function WindowSetTitle(title) {
  return window.runtime.WindowSetTitle(title);
}

export function WindowFullscreen() {
  return window.runtime.WindowFullscreen();
}

export function WindowUnfullscreen() {
  return window.runtime.WindowUnfullscreen();
}

export function WindowIsFullscreen() {
  return window.runtime.WindowIsFullscreen();
}

export function WindowSetSize(width, height) {
  return window.runtime.WindowSetSize(width, height);
}

export function WindowGetSize() {
  return window.runtime.WindowGetSize();
}

export function WindowSetMaxSize(width, height) {
  return window.runtime.WindowSetMaxSize(width, height);
}

export function WindowSetMinSize(width, height) {
  return window.runtime.WindowSetMinSize(width, height);
}

export function WindowSetPosition(x, y) {
  return window.runtime.WindowSetPosition(x, y);
}

export function WindowGetPosition() {
  return window.runtime.WindowGetPosition();
}

export function WindowHide() {
  return window.runtime.WindowHide();
}

export function WindowShow() {
  return window.runtime.WindowShow();
}

export function WindowMaximise() {
  return window.runtime.WindowMaximise();
}

export function WindowToggleMaximise() {
  return window.runtime.WindowToggleMaximise();
}

export function WindowUnmaximise() {
  return window.runtime.WindowUnmaximise();
}

export function WindowIsMaximised() {
  return window.runtime.WindowIsMaximised();
}

export function WindowMinimise() {
  return window.runtime.WindowMinimise();
}

export function WindowUnminimise() {
  return window.runtime.WindowUnminimise();
}

export function WindowSetBackgroundColour(R, G, B, A) {
  return window.runtime.WindowSetBackgroundColour(R, G, B, A);
}

export function ScreenGetAll() {
  return window.runtime.ScreenGetAll();
}

export function BrowserOpenURL(url) {
  return window.runtime.BrowserOpenURL(url);
}

export function Environment() {
  return window.runtime.Environment();
}

export function Quit() {
  return window.runtime.Quit();
}

export function Hide() {
  return window.runtime.Hide();
}

export function Show() {
  return window.runtime.Show();
}

export function ClipboardGetText() {
  return window.runtime.ClipboardGetText();
}

export function ClipboardSetText(text) {
  return window.runtime.ClipboardSetText(text);
}