// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLatestVersion():Promise<string>;

export function FileExists():Promise<boolean>;

export function ReadVersionFile():Promise<string>;

export function StartUpdate():Promise<string>;

export function Finish():Promise<string>;