// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLatestVersion() {
  return window['go']['main']['Updater']['FetchLatestVersion']();
}

export function FileExists() {
  return window['go']['main']['Updater']['FileExists']();
}

export function ReadVersionFile() {
  return window['go']['main']['Updater']['ReadVersionFile']();
}

export function StartUpdate() {
  return window['go']['main']['Updater']['StartUpdate']();
}

export function Finish() {
  return window['go']['main']['Updater']['Finish']();
}