name: CeroClient Build CI (FreeBSD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build inside FreeBSD VM
      uses: vmactions/freebsd-vm@v1
      with:
        release: 14.2
        usesh: true
        prepare: |
          env IGNORE_OSVERSION=yes pkg update -f
          echo "test paquet WebKit"
          pkg search -q webkit
          echo "test dépendances"
          env IGNORE_OSVERSION=yes pkg install -y python3 pkgconf webkit2-gtk3 curl git openjdk17

        run: |
          export PATH=$PATH:/usr/local/bin
          
          python3 build.py
          
          mkdir -p release
          cp bin/linux/client/CeroClient release/CeroClient-freebsd-x86_64
          cp bin/assets/assets.dat release/

    - name: Upload CeroClient Binary
      uses: actions/upload-artifact@v4
      with:
        name: CeroClient-freebsd-binaries
        path: release/CeroClient-freebsd-x86_64
        
    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: CeroClient-freebsd-assets
        path: release/assets.dat