name: CeroClient Build CI (FreeBSD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run build inside FreeBSD VM
      uses: vmactions/freebsd-vm@v1
      with:
        release: 14.2
        usesh: true
        prepare: |
          env IGNORE_OSVERSION=yes pkg update -f
          env IGNORE_OSVERSION=yes pkg install -y python3 pkgconf webkit2-gtk_41 curl git openjdk17 gmake bzip2 rust
          printf "Name: bzip2\nDescription: bzip2\nVersion: 1.0.8\nLibs: -lbz2\n" > /usr/local/libdata/pkgconfig/bzip2.pc
          
        run: |
          export PATH=$PATH:/usr/local/bin
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/usr/local/libdata/pkgconfig
          python3 build.py
          mkdir -p release
          cp bin/freebsd/client/CeroClient release/CeroClient-freebsd-x86_64
          cp bin/freebsd/bootstrapper/ceroclient-bootstrapper release/
          cp bin/assets/assets.dat release/

    - name: Upload CeroClient Binary
      uses: actions/upload-artifact@v4
      with:
        name: CeroClient-freebsd-binaries
        path: release/CeroClient-freebsd-x86_64
        
    - name: Upload Assets
      uses: actions/upload-artifact@v4
      with:
        name: CeroClient-freebsd-assets
        path: release/assets.dat